[package]
name = "methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0.git", rev = "c44f5a9be1c301de24962916c70a5dea98fe0aa1" }

[dependencies]
risc0-zkvm = { git = "https://github.com/risc0/risc0.git", rev = "c44f5a9be1c301de24962916c70a5dea98fe0aa1", default-features = false, features = ["std"] }
